from PySide2 import QtCore, QtGui, QtWidgets

from my_qt.table_model import CertificateTableModel, CompanyTableModel, EmployeeTableModel
from my_qt.table_views import TableView
from resources import MyStrings, url_back, url_plus, url_save, url_right_arrow
from utilities.data_structures import Bidict


class GDatabase:
    def __init__(self, window):
        self.w = window
        self.my_strings = MyStrings()

        self.setup_gui()
        self.button_ids = Bidict({
            self.w.buttonCertificates: 0,
            self.w.buttonIncoterms: 1,
            self.w.buttonMarks: 2,
            self.w.buttonCompanies: 3,
            self.w.buttonCompanyTypes: 4,
            self.w.buttonCompanyTiers: 5,
            self.w.buttonStaff: 6,
            self.w.buttonPanelTypes: 7,
            self.w.buttonCells: 8,
            self.w.buttonPanelNeeds: 9,
            self.w.buttonPanelQuotations: 10,
            self.w.buttonBosTypes: 11,
            self.w.buttonInverterTypes: 12,
            self.w.buttonStructureTypes: 13,
            self.w.buttonSolarSystems: 14,
            self.w.buttonAssessmentServices: 15,
            self.w.buttonProjectDevServices: 16,
            self.w.buttonSystemDesignServices: 17,
            self.w.buttonInstallConstructServices: 18,
            self.w.buttonOperMainServices: 19,
            self.w.buttonInsuranceServices: 20,
            self.w.buttonFinancialServices: 21,
            self.w.buttonLogisticServices: 22,
            self.w.buttonExtraServices: 23,
            self.w.buttonGeoZones: 24,
            self.w.buttonLanguages: 25,
            self.w.buttonPlaces: 26,
            self.w.buttonScopeRanges: 27,
            self.w.buttonUsers: 28
        })
        self.table_models = {
            0: CertificateTableModel,
            3: CompanyTableModel,
            6: EmployeeTableModel
        }

    # Edited: TableView
    def setup_gui(self):
        self.w.centralWidget = QtWidgets.QWidget(self.w)
        self.w.centralWidget.setObjectName('centralWidget')
        self.w.verticalLayout_3 = QtWidgets.QVBoxLayout(self.w.centralWidget)
        self.w.verticalLayout_3.setObjectName('verticalLayout_3')
        self.w.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.w.buttonBack = QtWidgets.QPushButton(self.w.centralWidget)
        self.w.buttonBack.setMinimumSize(QtCore.QSize(50, 40))
        self.w.buttonBack.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.w.buttonBack.setFont(font)
        self.w.buttonBack.setText('')
        self.w.buttonBack.setObjectName('buttonBack')
        self.w.horizontalLayout_4.addWidget(self.w.buttonBack)
        self.w.labelTitle = QtWidgets.QLabel(self.w.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.w.labelTitle.setFont(font)
        self.w.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelTitle.setObjectName('labelTitle')
        self.w.horizontalLayout_4.addWidget(self.w.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(50, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_4.addItem(spacerItem)
        self.w.verticalLayout_3.addLayout(self.w.horizontalLayout_4)
        self.w.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.w.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_2.setObjectName('verticalLayout_2')
        self.w.scrollArea = QtWidgets.QScrollArea(self.w.centralWidget)
        self.w.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.w.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.w.scrollArea.setLineWidth(2)
        self.w.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.w.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.w.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.w.scrollArea.setWidgetResizable(True)
        self.w.scrollArea.setObjectName('scrollArea')
        self.w.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.w.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 286, 1844))
        self.w.scrollAreaWidgetContents.setObjectName('scrollAreaWidgetContents')
        self.w.verticalLayout = QtWidgets.QVBoxLayout(self.w.scrollAreaWidgetContents)
        self.w.verticalLayout.setSpacing(0)
        self.w.verticalLayout.setObjectName('verticalLayout')
        self.w.labelGeneral = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelGeneral.setFont(font)
        self.w.labelGeneral.setWordWrap(False)
        self.w.labelGeneral.setObjectName('labelGeneral')
        self.w.verticalLayout.addWidget(self.w.labelGeneral)
        self.w.line_4 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_4.setObjectName('line_4')
        self.w.verticalLayout.addWidget(self.w.line_4)
        self.w.buttonCertificates = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonCertificates.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonCertificates.setFont(font)
        self.w.buttonCertificates.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonCertificates.setStyleSheet('text-align:left')
        self.w.buttonCertificates.setCheckable(True)
        self.w.buttonCertificates.setFlat(True)
        self.w.buttonCertificates.setObjectName('buttonCertificates')
        self.w.buttonGroup = QtWidgets.QButtonGroup(self.w.centralWidget)
        self.w.buttonGroup.setObjectName('buttonGroup')
        self.w.buttonGroup.addButton(self.w.buttonCertificates)
        self.w.verticalLayout.addWidget(self.w.buttonCertificates)
        self.w.buttonIncoterms = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonIncoterms.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonIncoterms.setFont(font)
        self.w.buttonIncoterms.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonIncoterms.setStyleSheet('text-align:left')
        self.w.buttonIncoterms.setCheckable(True)
        self.w.buttonIncoterms.setFlat(True)
        self.w.buttonIncoterms.setObjectName('buttonIncoterms')
        self.w.buttonGroup.addButton(self.w.buttonIncoterms)
        self.w.verticalLayout.addWidget(self.w.buttonIncoterms)
        self.w.buttonMarks = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonMarks.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonMarks.setFont(font)
        self.w.buttonMarks.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonMarks.setStyleSheet('text-align:left')
        self.w.buttonMarks.setCheckable(True)
        self.w.buttonMarks.setFlat(True)
        self.w.buttonMarks.setObjectName('buttonMarks')
        self.w.buttonGroup.addButton(self.w.buttonMarks)
        self.w.verticalLayout.addWidget(self.w.buttonMarks)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem1)
        self.w.labelCompanies = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelCompanies.setFont(font)
        self.w.labelCompanies.setWordWrap(False)
        self.w.labelCompanies.setObjectName('labelCompanies')
        self.w.verticalLayout.addWidget(self.w.labelCompanies)
        self.w.line_5 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_5.setObjectName('line_5')
        self.w.verticalLayout.addWidget(self.w.line_5)
        self.w.buttonCompanies = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonCompanies.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonCompanies.setFont(font)
        self.w.buttonCompanies.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonCompanies.setStyleSheet('text-align:left')
        self.w.buttonCompanies.setCheckable(True)
        self.w.buttonCompanies.setFlat(True)
        self.w.buttonCompanies.setObjectName('buttonCompanies')
        self.w.buttonGroup.addButton(self.w.buttonCompanies)
        self.w.verticalLayout.addWidget(self.w.buttonCompanies)
        self.w.buttonCompanyTypes = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonCompanyTypes.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonCompanyTypes.setFont(font)
        self.w.buttonCompanyTypes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonCompanyTypes.setStyleSheet('text-align:left')
        self.w.buttonCompanyTypes.setCheckable(True)
        self.w.buttonCompanyTypes.setFlat(True)
        self.w.buttonCompanyTypes.setObjectName('buttonCompanyTypes')
        self.w.buttonGroup.addButton(self.w.buttonCompanyTypes)
        self.w.verticalLayout.addWidget(self.w.buttonCompanyTypes)
        self.w.buttonCompanyTiers = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonCompanyTiers.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonCompanyTiers.setFont(font)
        self.w.buttonCompanyTiers.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonCompanyTiers.setStyleSheet('text-align:left')
        self.w.buttonCompanyTiers.setCheckable(True)
        self.w.buttonCompanyTiers.setFlat(True)
        self.w.buttonCompanyTiers.setObjectName('buttonCompanyTiers')
        self.w.buttonGroup.addButton(self.w.buttonCompanyTiers)
        self.w.verticalLayout.addWidget(self.w.buttonCompanyTiers)
        self.w.buttonStaff = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonStaff.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonStaff.setFont(font)
        self.w.buttonStaff.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonStaff.setStyleSheet('text-align:left')
        self.w.buttonStaff.setCheckable(True)
        self.w.buttonStaff.setFlat(True)
        self.w.buttonStaff.setObjectName('buttonStaff')
        self.w.buttonGroup.addButton(self.w.buttonStaff)
        self.w.verticalLayout.addWidget(self.w.buttonStaff)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem2)
        self.w.labelPanels = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelPanels.setFont(font)
        self.w.labelPanels.setWordWrap(False)
        self.w.labelPanels.setObjectName('labelPanels')
        self.w.verticalLayout.addWidget(self.w.labelPanels)
        self.w.line_6 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_6.setObjectName('line_6')
        self.w.verticalLayout.addWidget(self.w.line_6)
        self.w.buttonPanelTypes = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonPanelTypes.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonPanelTypes.setFont(font)
        self.w.buttonPanelTypes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonPanelTypes.setStyleSheet('text-align:left')
        self.w.buttonPanelTypes.setCheckable(True)
        self.w.buttonPanelTypes.setFlat(True)
        self.w.buttonPanelTypes.setObjectName('buttonPanelTypes')
        self.w.buttonGroup.addButton(self.w.buttonPanelTypes)
        self.w.verticalLayout.addWidget(self.w.buttonPanelTypes)
        self.w.buttonCells = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonCells.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonCells.setFont(font)
        self.w.buttonCells.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonCells.setStyleSheet('text-align:left')
        self.w.buttonCells.setCheckable(True)
        self.w.buttonCells.setFlat(True)
        self.w.buttonCells.setObjectName('buttonCells')
        self.w.buttonGroup.addButton(self.w.buttonCells)
        self.w.verticalLayout.addWidget(self.w.buttonCells)
        self.w.buttonPanelNeeds = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonPanelNeeds.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonPanelNeeds.setFont(font)
        self.w.buttonPanelNeeds.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonPanelNeeds.setStyleSheet('text-align:left')
        self.w.buttonPanelNeeds.setCheckable(True)
        self.w.buttonPanelNeeds.setFlat(True)
        self.w.buttonPanelNeeds.setObjectName('buttonPanelNeeds')
        self.w.buttonGroup.addButton(self.w.buttonPanelNeeds)
        self.w.verticalLayout.addWidget(self.w.buttonPanelNeeds)
        self.w.buttonPanelQuotations = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonPanelQuotations.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonPanelQuotations.setFont(font)
        self.w.buttonPanelQuotations.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonPanelQuotations.setStyleSheet('text-align:left')
        self.w.buttonPanelQuotations.setCheckable(True)
        self.w.buttonPanelQuotations.setFlat(True)
        self.w.buttonPanelQuotations.setObjectName('buttonPanelQuotations')
        self.w.buttonGroup.addButton(self.w.buttonPanelQuotations)
        self.w.verticalLayout.addWidget(self.w.buttonPanelQuotations)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem3)
        self.w.labelBos = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelBos.setFont(font)
        self.w.labelBos.setWordWrap(False)
        self.w.labelBos.setObjectName('labelBos')
        self.w.verticalLayout.addWidget(self.w.labelBos)
        self.w.line_2 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_2.setObjectName('line_2')
        self.w.verticalLayout.addWidget(self.w.line_2)
        self.w.buttonBosTypes = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonBosTypes.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonBosTypes.setFont(font)
        self.w.buttonBosTypes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonBosTypes.setStyleSheet('text-align:left')
        self.w.buttonBosTypes.setCheckable(True)
        self.w.buttonBosTypes.setFlat(True)
        self.w.buttonBosTypes.setObjectName('buttonBosTypes')
        self.w.buttonGroup.addButton(self.w.buttonBosTypes)
        self.w.verticalLayout.addWidget(self.w.buttonBosTypes)
        spacerItem4 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem4)
        self.w.labelInverters = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelInverters.setFont(font)
        self.w.labelInverters.setWordWrap(False)
        self.w.labelInverters.setObjectName('labelInverters')
        self.w.verticalLayout.addWidget(self.w.labelInverters)
        self.w.line_7 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_7.setObjectName('line_7')
        self.w.verticalLayout.addWidget(self.w.line_7)
        self.w.buttonInverterTypes = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonInverterTypes.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonInverterTypes.setFont(font)
        self.w.buttonInverterTypes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonInverterTypes.setStyleSheet('text-align:left')
        self.w.buttonInverterTypes.setCheckable(True)
        self.w.buttonInverterTypes.setFlat(True)
        self.w.buttonInverterTypes.setObjectName('buttonInverterTypes')
        self.w.buttonGroup.addButton(self.w.buttonInverterTypes)
        self.w.verticalLayout.addWidget(self.w.buttonInverterTypes)
        spacerItem5 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem5)
        self.w.labelStructures = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelStructures.setFont(font)
        self.w.labelStructures.setWordWrap(False)
        self.w.labelStructures.setObjectName('labelStructures')
        self.w.verticalLayout.addWidget(self.w.labelStructures)
        self.w.line_8 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_8.setObjectName('line_8')
        self.w.verticalLayout.addWidget(self.w.line_8)
        self.w.buttonStructureTypes = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonStructureTypes.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonStructureTypes.setFont(font)
        self.w.buttonStructureTypes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonStructureTypes.setStyleSheet('text-align:left')
        self.w.buttonStructureTypes.setCheckable(True)
        self.w.buttonStructureTypes.setFlat(True)
        self.w.buttonStructureTypes.setObjectName('buttonStructureTypes')
        self.w.buttonGroup.addButton(self.w.buttonStructureTypes)
        self.w.verticalLayout.addWidget(self.w.buttonStructureTypes)
        spacerItem6 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem6)
        self.w.labelSolarSystems = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelSolarSystems.setFont(font)
        self.w.labelSolarSystems.setWordWrap(False)
        self.w.labelSolarSystems.setObjectName('labelSolarSystems')
        self.w.verticalLayout.addWidget(self.w.labelSolarSystems)
        self.w.line_9 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_9.setObjectName('line_9')
        self.w.verticalLayout.addWidget(self.w.line_9)
        self.w.buttonSolarSystems = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonSolarSystems.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonSolarSystems.setFont(font)
        self.w.buttonSolarSystems.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonSolarSystems.setStyleSheet('text-align:left')
        self.w.buttonSolarSystems.setCheckable(True)
        self.w.buttonSolarSystems.setFlat(True)
        self.w.buttonSolarSystems.setObjectName('buttonSolarSystems')
        self.w.buttonGroup.addButton(self.w.buttonSolarSystems)
        self.w.verticalLayout.addWidget(self.w.buttonSolarSystems)
        spacerItem7 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem7)
        self.w.labelServices = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelServices.setFont(font)
        self.w.labelServices.setWordWrap(False)
        self.w.labelServices.setObjectName('labelServices')
        self.w.verticalLayout.addWidget(self.w.labelServices)
        self.w.line = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line.setObjectName('line')
        self.w.verticalLayout.addWidget(self.w.line)
        self.w.buttonAssessmentServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonAssessmentServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonAssessmentServices.setFont(font)
        self.w.buttonAssessmentServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonAssessmentServices.setStyleSheet('text-align:left')
        self.w.buttonAssessmentServices.setCheckable(True)
        self.w.buttonAssessmentServices.setFlat(True)
        self.w.buttonAssessmentServices.setObjectName('buttonAssessmentServices')
        self.w.buttonGroup.addButton(self.w.buttonAssessmentServices)
        self.w.verticalLayout.addWidget(self.w.buttonAssessmentServices)
        self.w.buttonProjectDevServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonProjectDevServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonProjectDevServices.setFont(font)
        self.w.buttonProjectDevServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonProjectDevServices.setStyleSheet('text-align:left')
        self.w.buttonProjectDevServices.setCheckable(True)
        self.w.buttonProjectDevServices.setFlat(True)
        self.w.buttonProjectDevServices.setObjectName('buttonProjectDevServices')
        self.w.buttonGroup.addButton(self.w.buttonProjectDevServices)
        self.w.verticalLayout.addWidget(self.w.buttonProjectDevServices)
        self.w.buttonSystemDesignServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonSystemDesignServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonSystemDesignServices.setFont(font)
        self.w.buttonSystemDesignServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonSystemDesignServices.setStyleSheet('text-align:left')
        self.w.buttonSystemDesignServices.setCheckable(True)
        self.w.buttonSystemDesignServices.setFlat(True)
        self.w.buttonSystemDesignServices.setObjectName('buttonSystemDesignServices')
        self.w.buttonGroup.addButton(self.w.buttonSystemDesignServices)
        self.w.verticalLayout.addWidget(self.w.buttonSystemDesignServices)
        self.w.buttonInstallConstructServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonInstallConstructServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonInstallConstructServices.setFont(font)
        self.w.buttonInstallConstructServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonInstallConstructServices.setStyleSheet('text-align:left')
        self.w.buttonInstallConstructServices.setCheckable(True)
        self.w.buttonInstallConstructServices.setFlat(True)
        self.w.buttonInstallConstructServices.setObjectName('buttonInstallConstructServices')
        self.w.buttonGroup.addButton(self.w.buttonInstallConstructServices)
        self.w.verticalLayout.addWidget(self.w.buttonInstallConstructServices)
        self.w.buttonOperMainServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonOperMainServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonOperMainServices.setFont(font)
        self.w.buttonOperMainServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonOperMainServices.setStyleSheet('text-align:left')
        self.w.buttonOperMainServices.setCheckable(True)
        self.w.buttonOperMainServices.setFlat(True)
        self.w.buttonOperMainServices.setObjectName('buttonOperMainServices')
        self.w.buttonGroup.addButton(self.w.buttonOperMainServices)
        self.w.verticalLayout.addWidget(self.w.buttonOperMainServices)
        self.w.buttonInsuranceServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonInsuranceServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonInsuranceServices.setFont(font)
        self.w.buttonInsuranceServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonInsuranceServices.setStyleSheet('text-align:left')
        self.w.buttonInsuranceServices.setCheckable(True)
        self.w.buttonInsuranceServices.setFlat(True)
        self.w.buttonInsuranceServices.setObjectName('buttonInsuranceServices')
        self.w.buttonGroup.addButton(self.w.buttonInsuranceServices)
        self.w.verticalLayout.addWidget(self.w.buttonInsuranceServices)
        self.w.buttonFinancialServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonFinancialServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonFinancialServices.setFont(font)
        self.w.buttonFinancialServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonFinancialServices.setStyleSheet('text-align:left')
        self.w.buttonFinancialServices.setCheckable(True)
        self.w.buttonFinancialServices.setFlat(True)
        self.w.buttonFinancialServices.setObjectName('buttonFinancialServices')
        self.w.buttonGroup.addButton(self.w.buttonFinancialServices)
        self.w.verticalLayout.addWidget(self.w.buttonFinancialServices)
        self.w.buttonLogisticServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonLogisticServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonLogisticServices.setFont(font)
        self.w.buttonLogisticServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonLogisticServices.setStyleSheet('text-align:left')
        self.w.buttonLogisticServices.setCheckable(True)
        self.w.buttonLogisticServices.setFlat(True)
        self.w.buttonLogisticServices.setObjectName('buttonLogisticServices')
        self.w.buttonGroup.addButton(self.w.buttonLogisticServices)
        self.w.verticalLayout.addWidget(self.w.buttonLogisticServices)
        self.w.buttonExtraServices = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonExtraServices.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonExtraServices.setFont(font)
        self.w.buttonExtraServices.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonExtraServices.setStyleSheet('text-align:left')
        self.w.buttonExtraServices.setCheckable(True)
        self.w.buttonExtraServices.setFlat(True)
        self.w.buttonExtraServices.setObjectName('buttonExtraServices')
        self.w.buttonGroup.addButton(self.w.buttonExtraServices)
        self.w.verticalLayout.addWidget(self.w.buttonExtraServices)
        spacerItem8 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem8)
        self.w.labelOthers = QtWidgets.QLabel(self.w.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.w.labelOthers.setFont(font)
        self.w.labelOthers.setWordWrap(False)
        self.w.labelOthers.setObjectName('labelOthers')
        self.w.verticalLayout.addWidget(self.w.labelOthers)
        self.w.line_3 = QtWidgets.QFrame(self.w.scrollAreaWidgetContents)
        self.w.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.w.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_3.setObjectName('line_3')
        self.w.verticalLayout.addWidget(self.w.line_3)
        self.w.buttonGeoZones = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonGeoZones.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonGeoZones.setFont(font)
        self.w.buttonGeoZones.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonGeoZones.setStyleSheet('text-align:left')
        self.w.buttonGeoZones.setCheckable(True)
        self.w.buttonGeoZones.setFlat(True)
        self.w.buttonGeoZones.setObjectName('buttonGeoZones')
        self.w.buttonGroup.addButton(self.w.buttonGeoZones)
        self.w.verticalLayout.addWidget(self.w.buttonGeoZones)
        self.w.buttonLanguages = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonLanguages.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonLanguages.setFont(font)
        self.w.buttonLanguages.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonLanguages.setStyleSheet('text-align:left')
        self.w.buttonLanguages.setCheckable(True)
        self.w.buttonLanguages.setFlat(True)
        self.w.buttonLanguages.setObjectName('buttonLanguages')
        self.w.buttonGroup.addButton(self.w.buttonLanguages)
        self.w.verticalLayout.addWidget(self.w.buttonLanguages)
        self.w.buttonPlaces = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonPlaces.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonPlaces.setFont(font)
        self.w.buttonPlaces.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonPlaces.setStyleSheet('text-align:left')
        self.w.buttonPlaces.setCheckable(True)
        self.w.buttonPlaces.setFlat(True)
        self.w.buttonPlaces.setObjectName('buttonPlaces')
        self.w.buttonGroup.addButton(self.w.buttonPlaces)
        self.w.verticalLayout.addWidget(self.w.buttonPlaces)
        self.w.buttonScopeRanges = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonScopeRanges.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonScopeRanges.setFont(font)
        self.w.buttonScopeRanges.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonScopeRanges.setStyleSheet('text-align:left')
        self.w.buttonScopeRanges.setCheckable(True)
        self.w.buttonScopeRanges.setFlat(True)
        self.w.buttonScopeRanges.setObjectName('buttonScopeRanges')
        self.w.buttonGroup.addButton(self.w.buttonScopeRanges)
        self.w.verticalLayout.addWidget(self.w.buttonScopeRanges)
        self.w.buttonUsers = QtWidgets.QPushButton(self.w.scrollAreaWidgetContents)
        self.w.buttonUsers.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.w.buttonUsers.setFont(font)
        self.w.buttonUsers.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w.buttonUsers.setStyleSheet('text-align:left')
        self.w.buttonUsers.setCheckable(True)
        self.w.buttonUsers.setFlat(True)
        self.w.buttonUsers.setObjectName('buttonUsers')
        self.w.buttonGroup.addButton(self.w.buttonUsers)
        self.w.verticalLayout.addWidget(self.w.buttonUsers)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout.addItem(spacerItem9)
        self.w.scrollArea.setWidget(self.w.scrollAreaWidgetContents)
        self.w.verticalLayout_2.addWidget(self.w.scrollArea)
        self.w.horizontalLayout_3.addLayout(self.w.verticalLayout_2)
        self.w.line_10 = QtWidgets.QFrame(self.w.centralWidget)
        self.w.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.w.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.w.line_10.setObjectName('line_10')
        self.w.horizontalLayout_3.addWidget(self.w.line_10)
        self.w.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_4.setObjectName('verticalLayout_4')
        self.w.tableView = TableView(self.my_strings, self.w.centralWidget)
        self.w.tableView.setObjectName('tableView')
        self.w.verticalLayout_4.addWidget(self.w.tableView)
        self.w.horizontalLayout = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout.setObjectName('horizontalLayout')
        self.w.labelTotal = QtWidgets.QLabel(self.w.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelTotal.setFont(font)
        self.w.labelTotal.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.w.labelTotal.setObjectName('labelTotal')
        self.w.horizontalLayout.addWidget(self.w.labelTotal)
        self.w.buttonAdd = QtWidgets.QPushButton(self.w.centralWidget)
        self.w.buttonAdd.setMinimumSize(QtCore.QSize(50, 30))
        self.w.buttonAdd.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.buttonAdd.setFont(font)
        self.w.buttonAdd.setText('')
        self.w.buttonAdd.setObjectName('buttonAdd')
        self.w.horizontalLayout.addWidget(self.w.buttonAdd)
        self.w.verticalLayout_4.addLayout(self.w.horizontalLayout)
        self.w.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_13.setSpacing(30)
        self.w.horizontalLayout_13.setObjectName('horizontalLayout_13')
        spacerItem10 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_13.addItem(spacerItem10)
        self.w.buttonSave = QtWidgets.QToolButton(self.w.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.buttonSave.sizePolicy().hasHeightForWidth())
        self.w.buttonSave.setSizePolicy(sizePolicy)
        self.w.buttonSave.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.w.buttonSave.setFont(font)
        self.w.buttonSave.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonSave.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.w.buttonSave.setObjectName('buttonSave')
        self.w.horizontalLayout_13.addWidget(self.w.buttonSave)
        spacerItem11 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_13.addItem(spacerItem11)
        self.w.verticalLayout_4.addLayout(self.w.horizontalLayout_13)
        self.w.horizontalLayout_3.addLayout(self.w.verticalLayout_4)
        self.w.horizontalLayout_3.setStretch(2, 1)
        self.w.verticalLayout_3.addLayout(self.w.horizontalLayout_3)
        self.w.setCentralWidget(self.w.centralWidget)

        self.w.labelTitle.setText(self.my_strings.title_database)
        self.w.labelGeneral.setText(self.my_strings.label_general)
        self.w.labelCompanies.setText(self.my_strings.label_companies)
        self.w.labelPanels.setText(self.my_strings.label_panels)
        self.w.labelBos.setText(self.my_strings.label_bos)
        self.w.labelInverters.setText(self.my_strings.label_inverters)
        self.w.labelStructures.setText(self.my_strings.label_structures)
        self.w.labelSolarSystems.setText(self.my_strings.label_solar_systems)
        self.w.labelServices.setText(self.my_strings.label_services)
        self.w.labelOthers.setText(self.my_strings.label_others)
        self.w.labelTotal.setText(f'{self.my_strings.label_total}:')

        self.w.buttonBack.setIcon(QtGui.QIcon(url_back))
        self.w.buttonBack.setIconSize(QtCore.QSize(32, 32))
        self.w.buttonSave.setText(self.my_strings.button_save)
        self.w.buttonSave.setIcon(QtGui.QIcon(url_save))
        self.w.buttonSave.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonCertificates.setText(self.my_strings.button_certificates)
        self.w.buttonCertificates.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonIncoterms.setText(self.my_strings.button_incoterms)
        self.w.buttonIncoterms.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonMarks.setText(self.my_strings.button_marks)
        self.w.buttonMarks.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonCompanies.setText(self.my_strings.button_companies)
        self.w.buttonCompanies.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonCompanyTiers.setText(self.my_strings.button_company_tiers)
        self.w.buttonCompanyTiers.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonCompanyTypes.setText(self.my_strings.button_company_types)
        self.w.buttonCompanyTypes.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonStaff.setText(self.my_strings.button_staff)
        self.w.buttonStaff.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonPanelTypes.setText(self.my_strings.button_panel_types)
        self.w.buttonPanelTypes.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonCells.setText(self.my_strings.button_cells)
        self.w.buttonCells.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonPanelNeeds.setText(self.my_strings.button_panel_needs)
        self.w.buttonPanelNeeds.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonPanelQuotations.setText(self.my_strings.button_panel_quotations)
        self.w.buttonPanelQuotations.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonBosTypes.setText(self.my_strings.button_bos_types)
        self.w.buttonBosTypes.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonInverterTypes.setText(self.my_strings.button_inverter_types)
        self.w.buttonInverterTypes.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonStructureTypes.setText(self.my_strings.button_structure_types)
        self.w.buttonStructureTypes.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonSolarSystems.setText(self.my_strings.button_solar_systems)
        self.w.buttonSolarSystems.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonAssessmentServices.setText(self.my_strings.button_assessment_services)
        self.w.buttonAssessmentServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonExtraServices.setText(self.my_strings.button_extra_services)
        self.w.buttonExtraServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonFinancialServices.setText(self.my_strings.button_financial_services)
        self.w.buttonFinancialServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonInstallConstructServices.setText(self.my_strings.button_install_construct_services)
        self.w.buttonInstallConstructServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonInsuranceServices.setText(self.my_strings.button_insurance_services)
        self.w.buttonInsuranceServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonLogisticServices.setText(self.my_strings.button_logistic_services)
        self.w.buttonLogisticServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonOperMainServices.setText(self.my_strings.button_oper_main_services)
        self.w.buttonOperMainServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonProjectDevServices.setText(self.my_strings.button_project_dev_services)
        self.w.buttonProjectDevServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonSystemDesignServices.setText(self.my_strings.button_system_design_services)
        self.w.buttonSystemDesignServices.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonGeoZones.setText(self.my_strings.button_geo_zones)
        self.w.buttonGeoZones.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonLanguages.setText(self.my_strings.button_languages)
        self.w.buttonLanguages.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonPlaces.setText(self.my_strings.button_places)
        self.w.buttonPlaces.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonScopeRanges.setText(self.my_strings.button_scope_ranges)
        self.w.buttonScopeRanges.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonUsers.setText(self.my_strings.button_users)
        self.w.buttonUsers.setIcon(QtGui.QIcon(url_right_arrow))
        self.w.buttonAdd.setIcon(QtGui.QIcon(url_plus))
        self.w.buttonAdd.setIconSize(QtCore.QSize(12, 12))

        self.hide_button_save()
        self.hide_table()

    def connect_signals(self, controller):
        self.w.buttonBack.clicked.connect(controller.clicked_back)
        self.w.buttonSave.clicked.connect(controller.save)
        self.w.buttonGroup.buttonClicked.connect(controller.clicked_button)
        self.w.buttonAdd.clicked.connect(controller.clicked_add)

        self.w.tableView.connect_signals(controller)

    @property
    def cheked_button_index(self):
        return self.button_ids[self.w.buttonGroup.checkedButton()]

    def click_button(self, index):
        self.button_ids.inverse[index][0].click()

    def load_table_data(self, headers, table_data, function_data_changed):
        self.w.tableView.setModel(self.table_models[self.cheked_button_index](self.w.tableView,
                                                                              headers,
                                                                              table_data,
                                                                              function_data_changed))
        self.w.labelTotal.setText(f'{self.my_strings.label_total}: {self.w.tableView.model().rowCount()}')

    def hide_button_save(self):
        self.w.buttonSave.hide()

    def hide_table(self):
        self.w.tableView.hide()
        self.w.labelTotal.hide()
        self.w.buttonAdd.hide()

    def show_button_save(self):
        self.w.buttonSave.show()

    def show_table(self):
        self.w.tableView.show()
        self.w.labelTotal.show()
        self.w.buttonAdd.show()
