from PySide2 import QtCore, QtGui, QtWidgets

from resources import MyStrings, url_logo, url_flag_eng, url_flag_spa, url_logo_database


class GMenu:
    def __init__(self, window):
        self.w = window
        self.my_strings = MyStrings()

        self.setup_gui()

    def setup_gui(self):
        self.w.centralWidget = QtWidgets.QWidget(self.w)
        self.w.centralWidget.setObjectName('centralWidget')
        self.w.verticalLayout = QtWidgets.QVBoxLayout(self.w.centralWidget)
        self.w.verticalLayout.setObjectName('verticalLayout')
        self.w.horizontalLayout = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout.setObjectName('horizontalLayout')
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout.addItem(spacerItem)
        self.w.buttonLanguage = QtWidgets.QToolButton(self.w.centralWidget)
        self.w.buttonLanguage.setMinimumSize(QtCore.QSize(35, 25))
        self.w.buttonLanguage.setMaximumSize(QtCore.QSize(35, 25))
        self.w.buttonLanguage.setText('')
        self.w.buttonLanguage.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.w.buttonLanguage.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.w.buttonLanguage.setAutoRaise(False)
        self.w.buttonLanguage.setArrowType(QtCore.Qt.NoArrow)
        self.w.buttonLanguage.setObjectName('buttonLanguage')
        self.w.horizontalLayout.addWidget(self.w.buttonLanguage)
        self.w.verticalLayout.addLayout(self.w.horizontalLayout)
        self.w.labelTitle = QtWidgets.QLabel(self.w.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.w.labelTitle.setFont(font)
        self.w.labelTitle.setText('')
        self.w.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelTitle.setObjectName('labelTitle')
        self.w.verticalLayout.addWidget(self.w.labelTitle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout.addItem(spacerItem1)
        self.w.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_2.setObjectName('horizontalLayout_2')
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_2.addItem(spacerItem2)
        self.w.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_2.setSpacing(30)
        self.w.verticalLayout_2.setObjectName('verticalLayout_2')
        self.w.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_3.setSpacing(20)
        self.w.verticalLayout_3.setObjectName('verticalLayout_3')
        self.w.buttonNeeds = QtWidgets.QPushButton(self.w.centralWidget)
        self.w.buttonNeeds.setMinimumSize(QtCore.QSize(400, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.w.buttonNeeds.setFont(font)
        self.w.buttonNeeds.setAutoDefault(True)
        self.w.buttonNeeds.setObjectName('buttonNeeds')
        self.w.verticalLayout_3.addWidget(self.w.buttonNeeds)
        self.w.buttonQuotations = QtWidgets.QPushButton(self.w.centralWidget)
        self.w.buttonQuotations.setMinimumSize(QtCore.QSize(400, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.w.buttonQuotations.setFont(font)
        self.w.buttonQuotations.setAutoDefault(True)
        self.w.buttonQuotations.setObjectName('buttonQuotations')
        self.w.verticalLayout_3.addWidget(self.w.buttonQuotations)
        self.w.verticalLayout_2.addLayout(self.w.verticalLayout_3)
        self.w.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_3.setObjectName('horizontalLayout_3')
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_3.addItem(spacerItem3)
        self.w.buttonDatabase = QtWidgets.QPushButton(self.w.centralWidget)
        self.w.buttonDatabase.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.w.buttonDatabase.setFont(font)
        self.w.buttonDatabase.setText('')
        self.w.buttonDatabase.setAutoDefault(True)
        self.w.buttonDatabase.setObjectName('buttonDatabase')
        self.w.horizontalLayout_3.addWidget(self.w.buttonDatabase)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_3.addItem(spacerItem4)
        self.w.verticalLayout_2.addLayout(self.w.horizontalLayout_3)
        self.w.horizontalLayout_2.addLayout(self.w.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_2.addItem(spacerItem5)
        self.w.verticalLayout.addLayout(self.w.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout.addItem(spacerItem6)
        self.w.verticalLayout.setStretch(2, 1)
        self.w.verticalLayout.setStretch(4, 2)
        self.w.setCentralWidget(self.w.centralWidget)

        self.w.labelTitle.setPixmap(QtGui.QPixmap(url_logo).scaled(QtCore.QSize(700,500), QtCore.Qt.KeepAspectRatio))

        self.w.buttonLanguage.setIcon(self.my_strings.icon_language)
        self.w.buttonLanguage.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonNeeds.setText(self.my_strings.title_needs)
        self.w.buttonNeeds.setStyleSheet('background-color: rgb(220, 245, 220)')
        self.w.buttonQuotations.setText(self.my_strings.title_quotations)
        self.w.buttonQuotations.setStyleSheet('background-color: rgb(210, 235, 245)')
        self.w.buttonDatabase.setIcon(QtGui.QIcon(url_logo_database))
        self.w.buttonDatabase.setIconSize(QtCore.QSize(38, 38))

    def connect_signals(self, controller):
        menu = QtWidgets.QMenu(self.w.buttonLanguage)
        menu.addAction(QtGui.QIcon(url_flag_spa), 'Español', lambda: controller.clicked_button_language('spa'))
        menu.addAction(QtGui.QIcon(url_flag_eng), 'English', lambda: controller.clicked_button_language('eng'))
        self.w.buttonLanguage.setMenu(menu)
        # self.w.buttonLanguage.setStyleSheet('QToolButton::menu-indicator { image: none; }')
        self.w.buttonNeeds.clicked.connect(lambda: controller.c_master.setup_needs())
        self.w.buttonQuotations.clicked.connect(lambda: controller.c_master.setup_quotations())
        self.w.buttonDatabase.clicked.connect(lambda: controller.c_master.setup_database())
