from collections import namedtuple

from PySide2 import QtCore, QtGui, QtWidgets

from guis.g_need import GNeed
from guis.g_panel import GPanel
from guis.g_price_bar_chart import GPriceBarChart
from my_qt.buttons import CheckableMenuButton
from my_qt.charts import PriceBarChart
from my_qt.combo_boxes import SearchCombo
from my_qt.group_boxes import RelatedPanelQuotationGroup
from my_qt.spin_boxes import NoWheelSpinBox, NoWheelDoubleSpinBox
from resources import url_back, url_save, url_plus, url_minus
from utilities.various import color_gray, color_red


class GPanelNeed(GPriceBarChart, GPanel, GNeed):
    def __init__(self, window):
        super(GPriceBarChart, self).__init__()
        super(GPanel, self).__init__(window)

        self.setup_gui()

    # Edited: SearchCombo, CheckableMenuButton, NoWheelSpinBox, NoWheelDoubleSpinBox, RelatedPanelQuotationGroup(+delete below), PriceBarChart(+delete below)
    def setup_gui(self):
        self.w.centralWidget = QtWidgets.QWidget(self.w)
        self.w.centralWidget.setObjectName('centralWidget')
        self.w.verticalLayout = QtWidgets.QVBoxLayout(self.w.centralWidget)
        self.w.verticalLayout.setSpacing(16)
        self.w.verticalLayout.setObjectName('verticalLayout')
        self.w.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_3.setSpacing(0)
        self.w.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.w.buttonBack = QtWidgets.QPushButton(self.w.centralWidget)
        self.w.buttonBack.setMinimumSize(QtCore.QSize(50, 40))
        self.w.buttonBack.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.w.buttonBack.setFont(font)
        self.w.buttonBack.setText('')
        self.w.buttonBack.setObjectName('buttonBack')
        self.w.horizontalLayout_3.addWidget(self.w.buttonBack)
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_3.addItem(spacerItem)
        self.w.labelTitle = QtWidgets.QLabel(self.w.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.w.labelTitle.setFont(font)
        self.w.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelTitle.setObjectName('labelTitle')
        self.w.horizontalLayout_3.addWidget(self.w.labelTitle)
        self.w.checkPriorities = QtWidgets.QCheckBox(self.w.centralWidget)
        self.w.checkPriorities.setMinimumSize(QtCore.QSize(170, 40))
        self.w.checkPriorities.setMaximumSize(QtCore.QSize(170, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.w.checkPriorities.setFont(font)
        self.w.checkPriorities.setTristate(False)
        self.w.checkPriorities.setObjectName('checkPriorities')
        self.w.horizontalLayout_3.addWidget(self.w.checkPriorities)
        self.w.verticalLayout.addLayout(self.w.horizontalLayout_3)
        self.w.scrollArea = QtWidgets.QScrollArea(self.w.centralWidget)
        self.w.scrollArea.setWidgetResizable(True)
        self.w.scrollArea.setObjectName('scrollArea')
        self.w.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.w.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1225, 861))
        self.w.scrollAreaWidgetContents.setObjectName('scrollAreaWidgetContents')
        self.w.verticalLayout_9 = QtWidgets.QVBoxLayout(self.w.scrollAreaWidgetContents)
        self.w.verticalLayout_9.setSpacing(20)
        self.w.verticalLayout_9.setObjectName('verticalLayout_9')
        self.w.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_4.setSpacing(50)
        self.w.horizontalLayout_4.setObjectName('horizontalLayout_4')
        spacerItem1 = QtWidgets.QSpacerItem(29, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_4.addItem(spacerItem1)
        self.w.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_2.setObjectName('verticalLayout_2')
        self.w.groupGeneral = QtWidgets.QGroupBox(self.w.scrollAreaWidgetContents)
        self.w.groupGeneral.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.w.groupGeneral.setFont(font)
        self.w.groupGeneral.setAlignment(QtCore.Qt.AlignCenter)
        self.w.groupGeneral.setObjectName('groupGeneral')
        self.w.verticalLayout_3 = QtWidgets.QVBoxLayout(self.w.groupGeneral)
        self.w.verticalLayout_3.setSpacing(20)
        self.w.verticalLayout_3.setObjectName('verticalLayout_3')
        self.w.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_5.setSpacing(10)
        self.w.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.w.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_12.setSpacing(2)
        self.w.verticalLayout_12.setObjectName('verticalLayout_12')
        self.w.labelCompany = QtWidgets.QLabel(self.w.groupGeneral)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelCompany.setFont(font)
        self.w.labelCompany.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelCompany.setObjectName('labelCompany')
        self.w.verticalLayout_12.addWidget(self.w.labelCompany)
        self.w.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_6.setObjectName('horizontalLayout_6')
        self.w.comboCompany = SearchCombo(self.w.groupGeneral)
        self.w.comboCompany.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboCompany.setFont(font)
        self.w.comboCompany.setObjectName('comboCompany')
        self.w.horizontalLayout_6.addWidget(self.w.comboCompany)
        self.w.buttonAddCompany = QtWidgets.QPushButton(self.w.groupGeneral)
        self.w.buttonAddCompany.setMinimumSize(QtCore.QSize(30, 30))
        self.w.buttonAddCompany.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.buttonAddCompany.setFont(font)
        self.w.buttonAddCompany.setText('')
        self.w.buttonAddCompany.setObjectName('buttonAddCompany')
        self.w.horizontalLayout_6.addWidget(self.w.buttonAddCompany)
        self.w.verticalLayout_12.addLayout(self.w.horizontalLayout_6)
        self.w.horizontalLayout_5.addLayout(self.w.verticalLayout_12)
        self.w.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_31.setSpacing(2)
        self.w.verticalLayout_31.setObjectName('verticalLayout_31')
        self.w.labelPrioCompany = QtWidgets.QLabel(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioCompany.sizePolicy().hasHeightForWidth())
        self.w.labelPrioCompany.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioCompany.setFont(font)
        self.w.labelPrioCompany.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioCompany.setObjectName('labelPrioCompany')
        self.w.verticalLayout_31.addWidget(self.w.labelPrioCompany)
        self.w.comboPrioCompany = QtWidgets.QComboBox(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioCompany.sizePolicy().hasHeightForWidth())
        self.w.comboPrioCompany.setSizePolicy(sizePolicy)
        self.w.comboPrioCompany.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioCompany.setFont(font)
        self.w.comboPrioCompany.setObjectName('comboPrioCompany')
        self.w.verticalLayout_31.addWidget(self.w.comboPrioCompany)
        self.w.horizontalLayout_5.addLayout(self.w.verticalLayout_31)
        self.w.horizontalLayout_5.setStretch(0, 1)
        self.w.verticalLayout_3.addLayout(self.w.horizontalLayout_5)
        self.w.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_7.setSpacing(10)
        self.w.horizontalLayout_7.setObjectName('horizontalLayout_7')
        self.w.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_28.setSpacing(2)
        self.w.verticalLayout_28.setObjectName('verticalLayout_28')
        self.w.labelMark = QtWidgets.QLabel(self.w.groupGeneral)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelMark.setFont(font)
        self.w.labelMark.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelMark.setObjectName('labelMark')
        self.w.verticalLayout_28.addWidget(self.w.labelMark)
        self.w.comboMark = SearchCombo(self.w.groupGeneral)
        self.w.comboMark.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboMark.setFont(font)
        self.w.comboMark.setObjectName('comboMark')
        self.w.verticalLayout_28.addWidget(self.w.comboMark)
        self.w.horizontalLayout_7.addLayout(self.w.verticalLayout_28)
        self.w.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_79.setSpacing(2)
        self.w.verticalLayout_79.setObjectName('verticalLayout_79')
        self.w.labelPrioMark = QtWidgets.QLabel(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioMark.sizePolicy().hasHeightForWidth())
        self.w.labelPrioMark.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioMark.setFont(font)
        self.w.labelPrioMark.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioMark.setObjectName('labelPrioMark')
        self.w.verticalLayout_79.addWidget(self.w.labelPrioMark)
        self.w.comboPrioMark = QtWidgets.QComboBox(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioMark.sizePolicy().hasHeightForWidth())
        self.w.comboPrioMark.setSizePolicy(sizePolicy)
        self.w.comboPrioMark.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioMark.setFont(font)
        self.w.comboPrioMark.setObjectName('comboPrioMark')
        self.w.verticalLayout_79.addWidget(self.w.comboPrioMark)
        self.w.horizontalLayout_7.addLayout(self.w.verticalLayout_79)
        self.w.horizontalLayout_7.setStretch(0, 1)
        self.w.verticalLayout_3.addLayout(self.w.horizontalLayout_7)
        self.w.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_9.setSpacing(10)
        self.w.horizontalLayout_9.setObjectName('horizontalLayout_9')
        self.w.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_13.setSpacing(2)
        self.w.verticalLayout_13.setObjectName('verticalLayout_13')
        self.w.labelTotalPower = QtWidgets.QLabel(self.w.groupGeneral)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelTotalPower.setFont(font)
        self.w.labelTotalPower.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelTotalPower.setObjectName('labelTotalPower')
        self.w.verticalLayout_13.addWidget(self.w.labelTotalPower)
        self.w.spinTotalPower = NoWheelDoubleSpinBox(self.w.groupGeneral)
        self.w.spinTotalPower.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.spinTotalPower.setFont(font)
        self.w.spinTotalPower.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w.spinTotalPower.setDecimals(3)
        self.w.spinTotalPower.setMaximum(9999999999.0)
        self.w.spinTotalPower.setObjectName('spinTotalPower')
        self.w.verticalLayout_13.addWidget(self.w.spinTotalPower)
        self.w.horizontalLayout_9.addLayout(self.w.verticalLayout_13)
        self.w.verticalLayout_80 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_80.setSpacing(2)
        self.w.verticalLayout_80.setObjectName('verticalLayout_80')
        self.w.labelPrioTotalPower = QtWidgets.QLabel(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioTotalPower.sizePolicy().hasHeightForWidth())
        self.w.labelPrioTotalPower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioTotalPower.setFont(font)
        self.w.labelPrioTotalPower.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioTotalPower.setObjectName('labelPrioTotalPower')
        self.w.verticalLayout_80.addWidget(self.w.labelPrioTotalPower)
        self.w.comboPrioTotalPower = QtWidgets.QComboBox(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioTotalPower.sizePolicy().hasHeightForWidth())
        self.w.comboPrioTotalPower.setSizePolicy(sizePolicy)
        self.w.comboPrioTotalPower.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioTotalPower.setFont(font)
        self.w.comboPrioTotalPower.setObjectName('comboPrioTotalPower')
        self.w.verticalLayout_80.addWidget(self.w.comboPrioTotalPower)
        self.w.horizontalLayout_9.addLayout(self.w.verticalLayout_80)
        self.w.horizontalLayout_9.setStretch(0, 1)
        self.w.verticalLayout_3.addLayout(self.w.horizontalLayout_9)
        self.w.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_15.setSpacing(10)
        self.w.horizontalLayout_15.setObjectName('horizontalLayout_15')
        self.w.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_14.setSpacing(2)
        self.w.verticalLayout_14.setObjectName('verticalLayout_14')
        self.w.labelPrice = QtWidgets.QLabel(self.w.groupGeneral)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrice.setFont(font)
        self.w.labelPrice.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelPrice.setObjectName('labelPrice')
        self.w.verticalLayout_14.addWidget(self.w.labelPrice)
        self.w.spinPrice = NoWheelDoubleSpinBox(self.w.groupGeneral)
        self.w.spinPrice.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.spinPrice.setFont(font)
        self.w.spinPrice.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w.spinPrice.setDecimals(4)
        self.w.spinPrice.setMaximum(9999999999.0)
        self.w.spinPrice.setObjectName('spinPrice')
        self.w.verticalLayout_14.addWidget(self.w.spinPrice)
        self.w.horizontalLayout_15.addLayout(self.w.verticalLayout_14)
        self.w.verticalLayout_87 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_87.setSpacing(2)
        self.w.verticalLayout_87.setObjectName('verticalLayout_87')
        self.w.labelPrioPrice = QtWidgets.QLabel(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioPrice.sizePolicy().hasHeightForWidth())
        self.w.labelPrioPrice.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioPrice.setFont(font)
        self.w.labelPrioPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioPrice.setObjectName('labelPrioPrice')
        self.w.verticalLayout_87.addWidget(self.w.labelPrioPrice)
        self.w.comboPrioPrice = QtWidgets.QComboBox(self.w.groupGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioPrice.sizePolicy().hasHeightForWidth())
        self.w.comboPrioPrice.setSizePolicy(sizePolicy)
        self.w.comboPrioPrice.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioPrice.setFont(font)
        self.w.comboPrioPrice.setObjectName('comboPrioPrice')
        self.w.verticalLayout_87.addWidget(self.w.comboPrioPrice)
        self.w.horizontalLayout_15.addLayout(self.w.verticalLayout_87)
        self.w.horizontalLayout_15.setStretch(0, 1)
        self.w.verticalLayout_3.addLayout(self.w.horizontalLayout_15)
        self.w.verticalLayout_2.addWidget(self.w.groupGeneral)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout_2.addItem(spacerItem2)
        self.w.horizontalLayout_4.addLayout(self.w.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_4.addItem(spacerItem3)
        self.w.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_4.setObjectName('verticalLayout_4')
        self.w.groupPanel = QtWidgets.QGroupBox(self.w.scrollAreaWidgetContents)
        self.w.groupPanel.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.w.groupPanel.setFont(font)
        self.w.groupPanel.setAlignment(QtCore.Qt.AlignCenter)
        self.w.groupPanel.setObjectName('groupPanel')
        self.w.verticalLayout_6 = QtWidgets.QVBoxLayout(self.w.groupPanel)
        self.w.verticalLayout_6.setSpacing(20)
        self.w.verticalLayout_6.setObjectName('verticalLayout_6')
        self.w.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_21.setSpacing(10)
        self.w.horizontalLayout_21.setObjectName('horizontalLayout_21')
        self.w.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_19.setSpacing(2)
        self.w.verticalLayout_19.setObjectName('verticalLayout_19')
        self.w.labelPanelType = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPanelType.setFont(font)
        self.w.labelPanelType.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelPanelType.setObjectName('labelPanelType')
        self.w.verticalLayout_19.addWidget(self.w.labelPanelType)
        self.w.buttonPanelTypes = CheckableMenuButton(self.w.groupPanel)
        self.w.buttonPanelTypes.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.buttonPanelTypes.setFont(font)
        self.w.buttonPanelTypes.setText('')
        self.w.buttonPanelTypes.setObjectName('buttonPanelTypes')
        self.w.verticalLayout_19.addWidget(self.w.buttonPanelTypes)
        self.w.horizontalLayout_21.addLayout(self.w.verticalLayout_19)
        self.w.verticalLayout_81 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_81.setSpacing(2)
        self.w.verticalLayout_81.setObjectName('verticalLayout_81')
        self.w.labelPrioPanelType = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioPanelType.sizePolicy().hasHeightForWidth())
        self.w.labelPrioPanelType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioPanelType.setFont(font)
        self.w.labelPrioPanelType.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioPanelType.setObjectName('labelPrioPanelType')
        self.w.verticalLayout_81.addWidget(self.w.labelPrioPanelType)
        self.w.comboPrioPanelType = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioPanelType.sizePolicy().hasHeightForWidth())
        self.w.comboPrioPanelType.setSizePolicy(sizePolicy)
        self.w.comboPrioPanelType.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioPanelType.setFont(font)
        self.w.comboPrioPanelType.setObjectName('comboPrioPanelType')
        self.w.verticalLayout_81.addWidget(self.w.comboPrioPanelType)
        self.w.horizontalLayout_21.addLayout(self.w.verticalLayout_81)
        self.w.horizontalLayout_21.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_21)
        self.w.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_22.setSpacing(10)
        self.w.horizontalLayout_22.setObjectName('horizontalLayout_22')
        self.w.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_20.setSpacing(2)
        self.w.verticalLayout_20.setObjectName('verticalLayout_20')
        self.w.labelCells = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelCells.setFont(font)
        self.w.labelCells.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelCells.setObjectName('labelCells')
        self.w.verticalLayout_20.addWidget(self.w.labelCells)
        self.w.buttonCells = CheckableMenuButton(self.w.groupPanel)
        self.w.buttonCells.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.buttonCells.setFont(font)
        self.w.buttonCells.setText('')
        self.w.buttonCells.setObjectName('buttonCells')
        self.w.verticalLayout_20.addWidget(self.w.buttonCells)
        self.w.horizontalLayout_22.addLayout(self.w.verticalLayout_20)
        self.w.verticalLayout_82 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_82.setSpacing(2)
        self.w.verticalLayout_82.setObjectName('verticalLayout_82')
        self.w.labelPrioCells = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioCells.sizePolicy().hasHeightForWidth())
        self.w.labelPrioCells.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioCells.setFont(font)
        self.w.labelPrioCells.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioCells.setObjectName('labelPrioCells')
        self.w.verticalLayout_82.addWidget(self.w.labelPrioCells)
        self.w.comboPrioCells = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioCells.sizePolicy().hasHeightForWidth())
        self.w.comboPrioCells.setSizePolicy(sizePolicy)
        self.w.comboPrioCells.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioCells.setFont(font)
        self.w.comboPrioCells.setObjectName('comboPrioCells')
        self.w.verticalLayout_82.addWidget(self.w.comboPrioCells)
        self.w.horizontalLayout_22.addLayout(self.w.verticalLayout_82)
        self.w.horizontalLayout_22.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_22)
        self.w.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_31.setSpacing(10)
        self.w.horizontalLayout_31.setObjectName('horizontalLayout_31')
        self.w.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_21.setSpacing(2)
        self.w.verticalLayout_21.setObjectName('verticalLayout_21')
        self.w.labelPanelPower = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPanelPower.setFont(font)
        self.w.labelPanelPower.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelPanelPower.setObjectName('labelPanelPower')
        self.w.verticalLayout_21.addWidget(self.w.labelPanelPower)
        self.w.spinPanelPower = NoWheelSpinBox(self.w.groupPanel)
        self.w.spinPanelPower.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.spinPanelPower.setFont(font)
        self.w.spinPanelPower.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w.spinPanelPower.setMaximum(999999999)
        self.w.spinPanelPower.setObjectName('spinPanelPower')
        self.w.verticalLayout_21.addWidget(self.w.spinPanelPower)
        self.w.horizontalLayout_31.addLayout(self.w.verticalLayout_21)
        self.w.verticalLayout_84 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_84.setSpacing(2)
        self.w.verticalLayout_84.setObjectName('verticalLayout_84')
        self.w.labelPrioPanelPower = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioPanelPower.sizePolicy().hasHeightForWidth())
        self.w.labelPrioPanelPower.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioPanelPower.setFont(font)
        self.w.labelPrioPanelPower.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioPanelPower.setObjectName('labelPrioPanelPower')
        self.w.verticalLayout_84.addWidget(self.w.labelPrioPanelPower)
        self.w.comboPrioPanelPower = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioPanelPower.sizePolicy().hasHeightForWidth())
        self.w.comboPrioPanelPower.setSizePolicy(sizePolicy)
        self.w.comboPrioPanelPower.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioPanelPower.setFont(font)
        self.w.comboPrioPanelPower.setObjectName('comboPrioPanelPower')
        self.w.verticalLayout_84.addWidget(self.w.comboPrioPanelPower)
        self.w.horizontalLayout_31.addLayout(self.w.verticalLayout_84)
        self.w.horizontalLayout_31.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_31)
        self.w.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_32.setSpacing(10)
        self.w.horizontalLayout_32.setObjectName('horizontalLayout_32')
        self.w.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_29.setSpacing(2)
        self.w.verticalLayout_29.setObjectName('verticalLayout_29')
        self.w.labelEfficiency = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelEfficiency.setFont(font)
        self.w.labelEfficiency.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelEfficiency.setObjectName('labelEfficiency')
        self.w.verticalLayout_29.addWidget(self.w.labelEfficiency)
        self.w.spinEfficiency = NoWheelDoubleSpinBox(self.w.groupPanel)
        self.w.spinEfficiency.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.spinEfficiency.setFont(font)
        self.w.spinEfficiency.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w.spinEfficiency.setDecimals(2)
        self.w.spinEfficiency.setMaximum(100.0)
        self.w.spinEfficiency.setObjectName('spinEfficiency')
        self.w.verticalLayout_29.addWidget(self.w.spinEfficiency)
        self.w.horizontalLayout_32.addLayout(self.w.verticalLayout_29)
        self.w.verticalLayout_85 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_85.setSpacing(2)
        self.w.verticalLayout_85.setObjectName('verticalLayout_85')
        self.w.labelPrioEfficiency = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioEfficiency.sizePolicy().hasHeightForWidth())
        self.w.labelPrioEfficiency.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioEfficiency.setFont(font)
        self.w.labelPrioEfficiency.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioEfficiency.setObjectName('labelPrioEfficiency')
        self.w.verticalLayout_85.addWidget(self.w.labelPrioEfficiency)
        self.w.comboPrioEfficiency = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioEfficiency.sizePolicy().hasHeightForWidth())
        self.w.comboPrioEfficiency.setSizePolicy(sizePolicy)
        self.w.comboPrioEfficiency.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioEfficiency.setFont(font)
        self.w.comboPrioEfficiency.setObjectName('comboPrioEfficiency')
        self.w.verticalLayout_85.addWidget(self.w.comboPrioEfficiency)
        self.w.horizontalLayout_32.addLayout(self.w.verticalLayout_85)
        self.w.horizontalLayout_32.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_32)
        self.w.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_33.setSpacing(10)
        self.w.horizontalLayout_33.setObjectName('horizontalLayout_33')
        self.w.groupTolerance = QtWidgets.QGroupBox(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.groupTolerance.setFont(font)
        self.w.groupTolerance.setObjectName('groupTolerance')
        self.w.verticalLayout_8 = QtWidgets.QVBoxLayout(self.w.groupTolerance)
        self.w.verticalLayout_8.setObjectName('verticalLayout_8')
        self.w.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_8.setObjectName('horizontalLayout_8')
        self.w.radioPositiveTolerance = QtWidgets.QRadioButton(self.w.groupTolerance)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.radioPositiveTolerance.setFont(font)
        self.w.radioPositiveTolerance.setChecked(True)
        self.w.radioPositiveTolerance.setObjectName('radioPositiveTolerance')
        self.w.buttonGroup = QtWidgets.QButtonGroup(self.w.centralWidget)
        self.w.buttonGroup.setObjectName('buttonGroup')
        self.w.buttonGroup.addButton(self.w.radioPositiveTolerance)
        self.w.horizontalLayout_8.addWidget(self.w.radioPositiveTolerance)
        self.w.radioNegativeTolerance = QtWidgets.QRadioButton(self.w.groupTolerance)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.radioNegativeTolerance.setFont(font)
        self.w.radioNegativeTolerance.setObjectName('radioNegativeTolerance')
        self.w.buttonGroup.addButton(self.w.radioNegativeTolerance)
        self.w.horizontalLayout_8.addWidget(self.w.radioNegativeTolerance)
        self.w.verticalLayout_8.addLayout(self.w.horizontalLayout_8)
        self.w.horizontalLayout_33.addWidget(self.w.groupTolerance)
        self.w.verticalLayout_86 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_86.setSpacing(2)
        self.w.verticalLayout_86.setObjectName('verticalLayout_86')
        self.w.labelPrioTolerance = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioTolerance.sizePolicy().hasHeightForWidth())
        self.w.labelPrioTolerance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioTolerance.setFont(font)
        self.w.labelPrioTolerance.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioTolerance.setObjectName('labelPrioTolerance')
        self.w.verticalLayout_86.addWidget(self.w.labelPrioTolerance)
        self.w.comboPrioTolerance = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioTolerance.sizePolicy().hasHeightForWidth())
        self.w.comboPrioTolerance.setSizePolicy(sizePolicy)
        self.w.comboPrioTolerance.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioTolerance.setFont(font)
        self.w.comboPrioTolerance.setObjectName('comboPrioTolerance')
        self.w.verticalLayout_86.addWidget(self.w.comboPrioTolerance)
        spacerItem4 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout_86.addItem(spacerItem4)
        self.w.horizontalLayout_33.addLayout(self.w.verticalLayout_86)
        self.w.horizontalLayout_33.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_33)
        self.w.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_34.setSpacing(10)
        self.w.horizontalLayout_34.setObjectName('horizontalLayout_34')
        self.w.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_32.setSpacing(2)
        self.w.verticalLayout_32.setObjectName('verticalLayout_32')
        self.w.labelWarrantyProduct = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelWarrantyProduct.setFont(font)
        self.w.labelWarrantyProduct.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelWarrantyProduct.setObjectName('labelWarrantyProduct')
        self.w.verticalLayout_32.addWidget(self.w.labelWarrantyProduct)
        self.w.spinWarrantyProduct = NoWheelSpinBox(self.w.groupPanel)
        self.w.spinWarrantyProduct.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.spinWarrantyProduct.setFont(font)
        self.w.spinWarrantyProduct.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w.spinWarrantyProduct.setMaximum(9999)
        self.w.spinWarrantyProduct.setObjectName('spinWarrantyProduct')
        self.w.verticalLayout_32.addWidget(self.w.spinWarrantyProduct)
        self.w.horizontalLayout_34.addLayout(self.w.verticalLayout_32)
        self.w.verticalLayout_88 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_88.setSpacing(2)
        self.w.verticalLayout_88.setObjectName('verticalLayout_88')
        self.w.labelPrioWarrantyProduct = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioWarrantyProduct.sizePolicy().hasHeightForWidth())
        self.w.labelPrioWarrantyProduct.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioWarrantyProduct.setFont(font)
        self.w.labelPrioWarrantyProduct.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioWarrantyProduct.setObjectName('labelPrioWarrantyProduct')
        self.w.verticalLayout_88.addWidget(self.w.labelPrioWarrantyProduct)
        self.w.comboPrioWarrantyProduct = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioWarrantyProduct.sizePolicy().hasHeightForWidth())
        self.w.comboPrioWarrantyProduct.setSizePolicy(sizePolicy)
        self.w.comboPrioWarrantyProduct.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioWarrantyProduct.setFont(font)
        self.w.comboPrioWarrantyProduct.setObjectName('comboPrioWarrantyProduct')
        self.w.verticalLayout_88.addWidget(self.w.comboPrioWarrantyProduct)
        self.w.horizontalLayout_34.addLayout(self.w.verticalLayout_88)
        self.w.horizontalLayout_34.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_34)
        self.w.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_35.setSpacing(10)
        self.w.horizontalLayout_35.setObjectName('horizontalLayout_35')
        self.w.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_33.setSpacing(2)
        self.w.verticalLayout_33.setObjectName('verticalLayout_33')
        self.w.labelWarrantyPerformance = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelWarrantyPerformance.setFont(font)
        self.w.labelWarrantyPerformance.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelWarrantyPerformance.setObjectName('labelWarrantyPerformance')
        self.w.verticalLayout_33.addWidget(self.w.labelWarrantyPerformance)
        self.w.spinWarrantyPerformance = NoWheelSpinBox(self.w.groupPanel)
        self.w.spinWarrantyPerformance.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.w.spinWarrantyPerformance.setFont(font)
        self.w.spinWarrantyPerformance.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w.spinWarrantyPerformance.setMaximum(9999)
        self.w.spinWarrantyPerformance.setObjectName('spinWarrantyPerformance')
        self.w.verticalLayout_33.addWidget(self.w.spinWarrantyPerformance)
        self.w.horizontalLayout_35.addLayout(self.w.verticalLayout_33)
        self.w.verticalLayout_89 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_89.setSpacing(2)
        self.w.verticalLayout_89.setObjectName('verticalLayout_89')
        self.w.labelPrioWarrantyPerformance = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioWarrantyPerformance.sizePolicy().hasHeightForWidth())
        self.w.labelPrioWarrantyPerformance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioWarrantyPerformance.setFont(font)
        self.w.labelPrioWarrantyPerformance.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioWarrantyPerformance.setObjectName('labelPrioWarrantyPerformance')
        self.w.verticalLayout_89.addWidget(self.w.labelPrioWarrantyPerformance)
        self.w.comboPrioWarrantyPerformance = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioWarrantyPerformance.sizePolicy().hasHeightForWidth())
        self.w.comboPrioWarrantyPerformance.setSizePolicy(sizePolicy)
        self.w.comboPrioWarrantyPerformance.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioWarrantyPerformance.setFont(font)
        self.w.comboPrioWarrantyPerformance.setObjectName('comboPrioWarrantyPerformance')
        self.w.verticalLayout_89.addWidget(self.w.comboPrioWarrantyPerformance)
        self.w.horizontalLayout_35.addLayout(self.w.verticalLayout_89)
        self.w.horizontalLayout_35.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_35)
        self.w.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_36.setSpacing(10)
        self.w.horizontalLayout_36.setObjectName('horizontalLayout_36')
        self.w.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_22.setSpacing(2)
        self.w.verticalLayout_22.setObjectName('verticalLayout_22')
        self.w.labelCertificates = QtWidgets.QLabel(self.w.groupPanel)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelCertificates.setFont(font)
        self.w.labelCertificates.setObjectName('labelCertificates')
        self.w.verticalLayout_22.addWidget(self.w.labelCertificates)
        self.w.buttonCertificates = CheckableMenuButton(self.w.groupPanel)
        self.w.buttonCertificates.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.buttonCertificates.setFont(font)
        self.w.buttonCertificates.setText('')
        self.w.buttonCertificates.setObjectName('buttonCertificates')
        self.w.verticalLayout_22.addWidget(self.w.buttonCertificates)
        self.w.horizontalLayout_36.addLayout(self.w.verticalLayout_22)
        self.w.verticalLayout_91 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_91.setSpacing(2)
        self.w.verticalLayout_91.setObjectName('verticalLayout_91')
        self.w.labelPrioCertificates = QtWidgets.QLabel(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioCertificates.sizePolicy().hasHeightForWidth())
        self.w.labelPrioCertificates.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioCertificates.setFont(font)
        self.w.labelPrioCertificates.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioCertificates.setObjectName('labelPrioCertificates')
        self.w.verticalLayout_91.addWidget(self.w.labelPrioCertificates)
        self.w.comboPrioCertificates = QtWidgets.QComboBox(self.w.groupPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioCertificates.sizePolicy().hasHeightForWidth())
        self.w.comboPrioCertificates.setSizePolicy(sizePolicy)
        self.w.comboPrioCertificates.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioCertificates.setFont(font)
        self.w.comboPrioCertificates.setObjectName('comboPrioCertificates')
        self.w.verticalLayout_91.addWidget(self.w.comboPrioCertificates)
        self.w.horizontalLayout_36.addLayout(self.w.verticalLayout_91)
        self.w.horizontalLayout_36.setStretch(0, 1)
        self.w.verticalLayout_6.addLayout(self.w.horizontalLayout_36)
        self.w.verticalLayout_4.addWidget(self.w.groupPanel)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout_4.addItem(spacerItem6)
        self.w.horizontalLayout_4.addLayout(self.w.verticalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_4.addItem(spacerItem7)
        self.w.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_11.setObjectName('verticalLayout_11')
        self.w.horizontalLayout = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout.setObjectName('horizontalLayout')
        spacerItem8 = QtWidgets.QSpacerItem(50, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout.addItem(spacerItem8)
        self.w.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_5.setObjectName('verticalLayout_5')
        self.w.groupGeographical = QtWidgets.QGroupBox(self.w.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.groupGeographical.sizePolicy().hasHeightForWidth())
        self.w.groupGeographical.setSizePolicy(sizePolicy)
        self.w.groupGeographical.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.w.groupGeographical.setFont(font)
        self.w.groupGeographical.setAlignment(QtCore.Qt.AlignCenter)
        self.w.groupGeographical.setObjectName('groupGeographical')
        self.w.verticalLayout_7 = QtWidgets.QVBoxLayout(self.w.groupGeographical)
        self.w.verticalLayout_7.setSpacing(20)
        self.w.verticalLayout_7.setObjectName('verticalLayout_7')
        self.w.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_37.setSpacing(10)
        self.w.horizontalLayout_37.setObjectName('horizontalLayout_37')
        self.w.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_23.setSpacing(2)
        self.w.verticalLayout_23.setObjectName('verticalLayout_23')
        self.w.labelIncoterm = QtWidgets.QLabel(self.w.groupGeographical)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelIncoterm.setFont(font)
        self.w.labelIncoterm.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelIncoterm.setObjectName('labelIncoterm')
        self.w.verticalLayout_23.addWidget(self.w.labelIncoterm)
        self.w.comboIncoterm = SearchCombo(self.w.groupGeographical)
        self.w.comboIncoterm.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboIncoterm.setFont(font)
        self.w.comboIncoterm.setObjectName('comboIncoterm')
        self.w.verticalLayout_23.addWidget(self.w.comboIncoterm)
        self.w.horizontalLayout_37.addLayout(self.w.verticalLayout_23)
        self.w.verticalLayout_90 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_90.setSpacing(2)
        self.w.verticalLayout_90.setObjectName('verticalLayout_90')
        self.w.labelPrioIncoterm = QtWidgets.QLabel(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioIncoterm.sizePolicy().hasHeightForWidth())
        self.w.labelPrioIncoterm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioIncoterm.setFont(font)
        self.w.labelPrioIncoterm.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioIncoterm.setObjectName('labelPrioIncoterm')
        self.w.verticalLayout_90.addWidget(self.w.labelPrioIncoterm)
        self.w.comboPrioIncoterm = QtWidgets.QComboBox(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioIncoterm.sizePolicy().hasHeightForWidth())
        self.w.comboPrioIncoterm.setSizePolicy(sizePolicy)
        self.w.comboPrioIncoterm.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioIncoterm.setFont(font)
        self.w.comboPrioIncoterm.setObjectName('comboPrioIncoterm')
        self.w.verticalLayout_90.addWidget(self.w.comboPrioIncoterm)
        self.w.horizontalLayout_37.addLayout(self.w.verticalLayout_90)
        self.w.horizontalLayout_37.setStretch(0, 1)
        self.w.verticalLayout_7.addLayout(self.w.horizontalLayout_37)
        self.w.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_38.setSpacing(10)
        self.w.horizontalLayout_38.setObjectName('horizontalLayout_38')
        self.w.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_24.setSpacing(2)
        self.w.verticalLayout_24.setObjectName('verticalLayout_24')
        self.w.labelMadeIn = QtWidgets.QLabel(self.w.groupGeographical)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelMadeIn.setFont(font)
        self.w.labelMadeIn.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelMadeIn.setObjectName('labelMadeIn')
        self.w.verticalLayout_24.addWidget(self.w.labelMadeIn)
        self.w.comboMadeIn = SearchCombo(self.w.groupGeographical)
        self.w.comboMadeIn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboMadeIn.setFont(font)
        self.w.comboMadeIn.setObjectName('comboMadeIn')
        self.w.verticalLayout_24.addWidget(self.w.comboMadeIn)
        self.w.horizontalLayout_38.addLayout(self.w.verticalLayout_24)
        self.w.verticalLayout_92 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_92.setSpacing(2)
        self.w.verticalLayout_92.setObjectName('verticalLayout_92')
        self.w.labelPrioMadeIn = QtWidgets.QLabel(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioMadeIn.sizePolicy().hasHeightForWidth())
        self.w.labelPrioMadeIn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioMadeIn.setFont(font)
        self.w.labelPrioMadeIn.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioMadeIn.setObjectName('labelPrioMadeIn')
        self.w.verticalLayout_92.addWidget(self.w.labelPrioMadeIn)
        self.w.comboPrioMadeIn = QtWidgets.QComboBox(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioMadeIn.sizePolicy().hasHeightForWidth())
        self.w.comboPrioMadeIn.setSizePolicy(sizePolicy)
        self.w.comboPrioMadeIn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioMadeIn.setFont(font)
        self.w.comboPrioMadeIn.setObjectName('comboPrioMadeIn')
        self.w.verticalLayout_92.addWidget(self.w.comboPrioMadeIn)
        self.w.horizontalLayout_38.addLayout(self.w.verticalLayout_92)
        self.w.horizontalLayout_38.setStretch(0, 1)
        self.w.verticalLayout_7.addLayout(self.w.horizontalLayout_38)
        self.w.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_39.setSpacing(10)
        self.w.horizontalLayout_39.setObjectName('horizontalLayout_39')
        self.w.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_25.setSpacing(2)
        self.w.verticalLayout_25.setObjectName('verticalLayout_25')
        self.w.labelOrigin = QtWidgets.QLabel(self.w.groupGeographical)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelOrigin.setFont(font)
        self.w.labelOrigin.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelOrigin.setObjectName('labelOrigin')
        self.w.verticalLayout_25.addWidget(self.w.labelOrigin)
        self.w.comboOrigin = SearchCombo(self.w.groupGeographical)
        self.w.comboOrigin.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboOrigin.setFont(font)
        self.w.comboOrigin.setObjectName('comboOrigin')
        self.w.verticalLayout_25.addWidget(self.w.comboOrigin)
        self.w.horizontalLayout_39.addLayout(self.w.verticalLayout_25)
        self.w.verticalLayout_93 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_93.setSpacing(2)
        self.w.verticalLayout_93.setObjectName('verticalLayout_93')
        self.w.labelPrioOrigin = QtWidgets.QLabel(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioOrigin.sizePolicy().hasHeightForWidth())
        self.w.labelPrioOrigin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioOrigin.setFont(font)
        self.w.labelPrioOrigin.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioOrigin.setObjectName('labelPrioOrigin')
        self.w.verticalLayout_93.addWidget(self.w.labelPrioOrigin)
        self.w.comboPrioOrigin = QtWidgets.QComboBox(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioOrigin.sizePolicy().hasHeightForWidth())
        self.w.comboPrioOrigin.setSizePolicy(sizePolicy)
        self.w.comboPrioOrigin.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioOrigin.setFont(font)
        self.w.comboPrioOrigin.setObjectName('comboPrioOrigin')
        self.w.verticalLayout_93.addWidget(self.w.comboPrioOrigin)
        self.w.horizontalLayout_39.addLayout(self.w.verticalLayout_93)
        self.w.horizontalLayout_39.setStretch(0, 1)
        self.w.verticalLayout_7.addLayout(self.w.horizontalLayout_39)
        self.w.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_40.setSpacing(10)
        self.w.horizontalLayout_40.setObjectName('horizontalLayout_40')
        self.w.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_26.setSpacing(2)
        self.w.verticalLayout_26.setObjectName('verticalLayout_26')
        self.w.labelDestination = QtWidgets.QLabel(self.w.groupGeographical)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelDestination.setFont(font)
        self.w.labelDestination.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.w.labelDestination.setObjectName('labelDestination')
        self.w.verticalLayout_26.addWidget(self.w.labelDestination)
        self.w.comboDestination = SearchCombo(self.w.groupGeographical)
        self.w.comboDestination.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboDestination.setFont(font)
        self.w.comboDestination.setObjectName('comboDestination')
        self.w.verticalLayout_26.addWidget(self.w.comboDestination)
        self.w.horizontalLayout_40.addLayout(self.w.verticalLayout_26)
        self.w.verticalLayout_94 = QtWidgets.QVBoxLayout()
        self.w.verticalLayout_94.setSpacing(2)
        self.w.verticalLayout_94.setObjectName('verticalLayout_94')
        self.w.labelPrioDestination = QtWidgets.QLabel(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.labelPrioDestination.sizePolicy().hasHeightForWidth())
        self.w.labelPrioDestination.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.w.labelPrioDestination.setFont(font)
        self.w.labelPrioDestination.setAlignment(QtCore.Qt.AlignCenter)
        self.w.labelPrioDestination.setObjectName('labelPrioDestination')
        self.w.verticalLayout_94.addWidget(self.w.labelPrioDestination)
        self.w.comboPrioDestination = QtWidgets.QComboBox(self.w.groupGeographical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.comboPrioDestination.sizePolicy().hasHeightForWidth())
        self.w.comboPrioDestination.setSizePolicy(sizePolicy)
        self.w.comboPrioDestination.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.w.comboPrioDestination.setFont(font)
        self.w.comboPrioDestination.setObjectName('comboPrioDestination')
        self.w.verticalLayout_94.addWidget(self.w.comboPrioDestination)
        self.w.horizontalLayout_40.addLayout(self.w.verticalLayout_94)
        self.w.horizontalLayout_40.setStretch(0, 1)
        self.w.verticalLayout_7.addLayout(self.w.horizontalLayout_40)
        self.w.verticalLayout_5.addWidget(self.w.groupGeographical)
        self.w.horizontalLayout.addLayout(self.w.verticalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(35, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout.addItem(spacerItem9)
        self.w.verticalLayout_11.addLayout(self.w.horizontalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout_11.addItem(spacerItem10)
        self.w.priceBarChart = PriceBarChart(self.my_strings)
        self.w.verticalLayout_11.addWidget(self.w.priceBarChart)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.w.verticalLayout_11.addItem(spacerItem11)
        self.w.verticalLayout_11.setStretch(2, 1)
        self.w.horizontalLayout_4.addLayout(self.w.verticalLayout_11)
        spacerItem12 = QtWidgets.QSpacerItem(35, 620, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_4.addItem(spacerItem12)
        self.w.horizontalLayout_4.setStretch(0, 2)
        self.w.horizontalLayout_4.setStretch(1, 4)
        self.w.horizontalLayout_4.setStretch(2, 2)
        self.w.horizontalLayout_4.setStretch(3, 4)
        self.w.horizontalLayout_4.setStretch(5, 5)
        self.w.horizontalLayout_4.setStretch(6, 2)
        self.w.verticalLayout_9.addLayout(self.w.horizontalLayout_4)
        self.w.groupRelatedPanelQuotations = RelatedPanelQuotationGroup(self.w.scrollAreaWidgetContents,
                                                                        self.my_strings)
        self.w.verticalLayout_9.addWidget(self.w.groupRelatedPanelQuotations)
        self.w.scrollArea.setWidget(self.w.scrollAreaWidgetContents)
        self.w.verticalLayout.addWidget(self.w.scrollArea)
        self.w.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.w.horizontalLayout_13.setSpacing(30)
        self.w.horizontalLayout_13.setObjectName('horizontalLayout_13')
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_13.addItem(spacerItem13)
        self.w.buttonNew = QtWidgets.QToolButton(self.w.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.buttonNew.sizePolicy().hasHeightForWidth())
        self.w.buttonNew.setSizePolicy(sizePolicy)
        self.w.buttonNew.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.w.buttonNew.setFont(font)
        self.w.buttonNew.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonNew.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.w.buttonNew.setObjectName('buttonNew')
        self.w.horizontalLayout_13.addWidget(self.w.buttonNew)
        self.w.buttonOverwrite = QtWidgets.QToolButton(self.w.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w.buttonOverwrite.sizePolicy().hasHeightForWidth())
        self.w.buttonOverwrite.setSizePolicy(sizePolicy)
        self.w.buttonOverwrite.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.w.buttonOverwrite.setFont(font)
        self.w.buttonOverwrite.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonOverwrite.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.w.buttonOverwrite.setObjectName('buttonOverwrite')
        self.w.horizontalLayout_13.addWidget(self.w.buttonOverwrite)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.w.horizontalLayout_13.addItem(spacerItem14)
        self.w.verticalLayout.addLayout(self.w.horizontalLayout_13)
        spacerItem15 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.w.verticalLayout.addItem(spacerItem15)
        self.w.setCentralWidget(self.w.centralWidget)

        self.w.labelTitle.setText(self.my_strings.title_panel_need)
        self.w.labelCompany.setText(color_gray(self.my_strings.label_company))
        self.w.labelMark.setText(color_gray(self.my_strings.label_mark))
        self.w.labelTotalPower.setText(f"{color_gray(self.my_strings.label_total_power)} {color_red('*')}")
        self.w.labelPrice.setText(f"{color_gray(self.my_strings.label_price)} {color_red('*')}")
        self.w.labelPanelType.setText(color_gray(self.my_strings.label_type))
        self.w.labelCells.setText(color_gray(self.my_strings.label_cells))
        self.w.labelPanelPower.setText(f"{color_gray(self.my_strings.label_panel_power)} {color_red('*')}")
        self.w.labelEfficiency.setText(color_gray(self.my_strings.label_efficiency))
        self.w.labelWarrantyProduct.setText(color_gray(self.my_strings.label_warranty_product))
        self.w.labelWarrantyPerformance.setText(color_gray(self.my_strings.label_warranty_performance))
        self.w.labelCertificates.setText(color_gray(self.my_strings.label_certificates))
        self.w.labelIncoterm.setText(color_gray(self.my_strings.label_incoterm))
        self.w.labelMadeIn.setText(color_gray(self.my_strings.label_made_in))
        self.w.labelOrigin.setText(color_gray(self.my_strings.label_origin))
        self.w.labelDestination.setText(color_gray(self.my_strings.label_destination))
        self.w.labelPrioCompany.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioMark.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioTotalPower.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioPrice.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioPanelType.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioCells.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioPanelPower.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioEfficiency.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioTolerance.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioWarrantyProduct.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioWarrantyPerformance.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioCertificates.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioIncoterm.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioMadeIn.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioOrigin.setText(color_gray(self.my_strings.label_priority))
        self.w.labelPrioDestination.setText(color_gray(self.my_strings.label_priority))

        self.w.buttonBack.setIcon(QtGui.QIcon(url_back))
        self.w.buttonBack.setIconSize(QtCore.QSize(32, 32))
        self.w.buttonNew.setIcon(QtGui.QIcon(url_save))
        self.w.buttonNew.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonNew.setText(self.my_strings.button_new)
        self.w.buttonOverwrite.setIcon(QtGui.QIcon(url_save))
        self.w.buttonOverwrite.setIconSize(QtCore.QSize(40, 40))
        self.w.buttonOverwrite.setText(self.my_strings.button_overwrite)
        self.w.buttonOverwrite.setVisible(False)
        self.w.buttonAddCompany.setIcon(QtGui.QIcon(url_plus))
        self.w.buttonAddCompany.setIconSize(QtCore.QSize(12, 12))

        self.w.checkPriorities.setText(self.my_strings.check_priorities)

        self.w.radioPositiveTolerance.setText(self.my_strings.radio_positive)
        self.w.radioNegativeTolerance.setText(self.my_strings.radio_negative)

        priority_levels = ('-', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16')
        self.w.comboPrioCompany.addItems(priority_levels)
        self.w.comboPrioMark.addItems(priority_levels)
        self.w.comboPrioTotalPower.addItems(priority_levels)
        self.w.comboPrioPrice.addItems(priority_levels)
        self.w.comboPrioPanelType.addItems(priority_levels)
        self.w.comboPrioCells.addItems(priority_levels)
        self.w.comboPrioPanelPower.addItems(priority_levels)
        self.w.comboPrioEfficiency.addItems(priority_levels)
        self.w.comboPrioTolerance.addItems(priority_levels)
        self.w.comboPrioWarrantyProduct.addItems(priority_levels)
        self.w.comboPrioWarrantyPerformance.addItems(priority_levels)
        self.w.comboPrioCertificates.addItems(priority_levels)
        self.w.comboPrioIncoterm.addItems(priority_levels)
        self.w.comboPrioMadeIn.addItems(priority_levels)
        self.w.comboPrioOrigin.addItems(priority_levels)
        self.w.comboPrioDestination.addItems(priority_levels)

        self.w.spinTotalPower.setSuffix(' kW')
        self.w.spinPrice.setSuffix(' €/W')
        self.w.spinPanelPower.setSuffix(' W')
        self.w.spinEfficiency.setSuffix(' %')
        self._update_suffix_year()

        self.w.groupGeneral.setTitle(self.my_strings.group_general)
        self.w.groupPanel.setTitle(self.my_strings.group_panel)
        self.w.groupGeographical.setTitle(self.my_strings.group_geographical)
        self.w.groupTolerance.setTitle(self.my_strings.group_tolerance)
        self.w.groupTolerance.setStyleSheet('QGroupBox:title {color: #555555}')

        self.set_priorities_visible(False)

        # Coloring
        self.w.centralWidget.setStyleSheet('.QWidget{background-color: rgb(232, 242, 232)}')

    def connect_signals(self, controller):
        super(GPanelNeed, self).connect_signals(controller)
        super(GPriceBarChart, self).connect_signals(controller)
        super(GPanel, self).connect_signals(controller)

        self.w.buttonPanelTypes.menu().aboutToHide.connect(controller.update_current_type_average)
        self.w.buttonPanelTypes.menu().aboutToHide.connect(controller.update_related_panel_quotations)
        self.w.buttonCells.menu().aboutToHide.connect(controller.update_related_panel_quotations)
        self.w.buttonCertificates.menu().aboutToHide.connect(controller.update_related_panel_quotations)

        self.w.checkPriorities.stateChanged.connect(controller.clicked_check_priorities)

        self.w.radioPositiveTolerance.toggled.connect(controller.update_related_panel_quotations)

        self.w.comboCompany.currentTextChanged.connect(lambda: self.w.comboCompany.validate_hard(ignore_empty=True))
        self.w.comboCompany.lineEdit().textChanged.connect(controller.changed)
        self.w.comboMark.lineEdit().textChanged.connect(controller.changed)
        self.w.comboIncoterm.lineEdit().textChanged.connect(controller.changed)
        self.w.comboMadeIn.lineEdit().textChanged.connect(controller.changed)
        self.w.comboOrigin.lineEdit().textChanged.connect(controller.changed)
        self.w.comboDestination.lineEdit().textChanged.connect(controller.changed)
        self.w.comboPrioCompany.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioMark.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioTotalPower.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioPrice.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioPanelType.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioCells.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioPanelPower.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioEfficiency.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioTolerance.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioWarrantyProduct.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioWarrantyPerformance.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioCertificates.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioIncoterm.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioMadeIn.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioOrigin.currentIndexChanged.connect(controller.update_related_panel_quotations)
        self.w.comboPrioDestination.currentIndexChanged.connect(controller.update_related_panel_quotations)

        self.w.spinTotalPower.valueChanged.connect(controller.changed)
        self.w.spinPrice.valueChanged.connect(controller.changed)
        self.w.spinPanelPower.valueChanged.connect(controller.changed)
        self.w.spinEfficiency.valueChanged.connect(controller.changed)
        self.w.spinWarrantyProduct.valueChanged.connect(controller.changed)
        self.w.spinWarrantyPerformance.valueChanged.connect(controller.changed)

        self.w.groupRelatedPanelQuotations.connect_signals(controller)

        self.w.signal_search.connect(controller.update_related_panel_quotations)

    @property
    def checked_cells(self):
        return self.w.buttonCells.checked_items

    @checked_cells.setter
    def checked_cells(self, items):
        self.w.buttonCells.checked_items = items

    @property
    def data(self):
        Data = namedtuple('Data',
                          ('company', 'mark', 'total_power', 'price', 'panel_types', 'cells', 'panel_power',
                           'efficiency', 'tolerance', 'warranty_product', 'warranty_performance', 'certificates',
                           'incoterm', 'made_in', 'origin', 'destination')
                          )
        return Data(
            self.company,
            self.mark,
            self.total_power,
            self.price,

            self.checked_panel_types,
            self.checked_cells,
            self.panel_power,
            self.efficiency,
            self.tolerance,
            self.warranty_product,
            self.warranty_performance,
            self.checked_certificates,

            self.incoterm,
            self.made_in,
            self.origin,
            self.destination
        )

    @property
    def checked_panel_types(self):
        return self.w.buttonPanelTypes.checked_items

    @checked_panel_types.setter
    def checked_panel_types(self, items):
        self.w.buttonPanelTypes.checked_items = items

    @property
    def priorities(self):
        return self.w.checkPriorities.isChecked()

    @property
    def priority_cells(self):
        return self.w.comboPrioCells.currentText()

    @property
    def priority_certificates(self):
        return self.w.comboPrioCertificates.currentText()

    @property
    def priority_company(self):
        return self.w.comboPrioCompany.currentText()

    @property
    def priority_destination(self):
        return self.w.comboPrioDestination.currentText()

    @property
    def priority_efficiency(self):
        return self.w.comboPrioEfficiency.currentText()

    @property
    def priority_incoterm(self):
        return self.w.comboPrioIncoterm.currentText()

    @property
    def priority_made_in(self):
        return self.w.comboPrioMadeIn.currentText()

    @property
    def priority_mark(self):
        return self.w.comboPrioMark.currentText()

    @property
    def priority_origin(self):
        return self.w.comboPrioOrigin.currentText()

    @property
    def priority_panel_power(self):
        return self.w.comboPrioPanelPower.currentText()

    @property
    def priority_panel_type(self):
        return self.w.comboPrioPanelType.currentText()

    @property
    def priority_price(self):
        return self.w.comboPrioPrice.currentText()

    @property
    def priority_tolerance(self):
        return self.w.comboPrioTolerance.currentText()

    @property
    def priority_total_power(self):
        return self.w.comboPrioTotalPower.currentText()

    @property
    def priority_warranty_performance(self):
        return self.w.comboPrioWarrantyPerformance.currentText()

    @property
    def priority_warranty_product(self):
        return self.w.comboPrioWarrantyProduct.currentText()

    @property
    def signal_search(self):
        return self.w.signal_search

    def load_initial_data(self,
                          company_names,
                          mark_names,
                          panel_type_names,
                          cells_numbers,
                          certificate_names,
                          incoterm_names,
                          place_names,
                          all_average,
                          default):
        self.w.comboCompany.items = company_names
        self.w.comboMark.items = mark_names
        self.w.buttonPanelTypes.items = panel_type_names
        self.w.buttonCells.items = cells_numbers
        self.w.buttonCertificates.items = certificate_names
        self.w.comboIncoterm.items = incoterm_names
        self.w.comboMadeIn.items = place_names
        self.w.comboOrigin.items = place_names
        self.w.comboDestination.items = place_names
        self.price_bar_chart_all_average = all_average

        if default:
            self.w.spinTotalPower.validate_hard()
            self.w.spinPrice.validate_hard()
            self.w.spinPanelPower.validate_hard()
        else:
            self.w.comboMark.validate_soft()
            self.w.comboIncoterm.validate_soft()
            self.w.comboMadeIn.validate_soft()
            self.w.comboOrigin.validate_soft()
            self.w.comboDestination.validate_soft()

    def load_item_data(self, panel_need):
        self.company = panel_need.company
        self.mark = panel_need.mark
        self.total_power = panel_need.total_power
        self.price = panel_need.price

        self.checked_panel_types = panel_need.panel_types
        self.checked_cells = panel_need.cells
        self.checked_certificates = panel_need.certificates
        self.panel_power = panel_need.panel_power
        self.efficiency = panel_need.efficiency
        self.tolerance = panel_need.tolerance
        self.warranty_product = panel_need.warranty_product
        self.warranty_performance = panel_need.warranty_performance
        self.checked_certificates = panel_need.certificates

        self.incoterm = panel_need.incoterm
        self.made_in = panel_need.made_in
        self.origin = panel_need.origin
        self.destination = panel_need.destination

    def load_related_panel_quotations(self, sorted_prioritized_panel_quotations):
        self.w.groupRelatedPanelQuotations.load_items(sorted_prioritized_panel_quotations)


    def set_priorities_visible(self, b: bool):
        self.w.labelPrioCompany.setVisible(b)
        self.w.labelPrioMark.setVisible(b)
        self.w.labelPrioTotalPower.setVisible(b)
        self.w.labelPrioPrice.setVisible(b)
        self.w.labelPrioPanelType.setVisible(b)
        self.w.labelPrioCells.setVisible(b)
        self.w.labelPrioPanelPower.setVisible(b)
        self.w.labelPrioEfficiency.setVisible(b)
        self.w.labelPrioTolerance.setVisible(b)
        self.w.labelPrioWarrantyProduct.setVisible(b)
        self.w.labelPrioWarrantyPerformance.setVisible(b)
        self.w.labelPrioCertificates.setVisible(b)
        self.w.labelPrioIncoterm.setVisible(b)
        self.w.labelPrioMadeIn.setVisible(b)
        self.w.labelPrioOrigin.setVisible(b)
        self.w.labelPrioDestination.setVisible(b)

        self.w.comboPrioCompany.setVisible(b)
        self.w.comboPrioMark.setVisible(b)
        self.w.comboPrioTotalPower.setVisible(b)
        self.w.comboPrioPrice.setVisible(b)
        self.w.comboPrioPanelType.setVisible(b)
        self.w.comboPrioCells.setVisible(b)
        self.w.comboPrioPanelPower.setVisible(b)
        self.w.comboPrioEfficiency.setVisible(b)
        self.w.comboPrioTolerance.setVisible(b)
        self.w.comboPrioWarrantyProduct.setVisible(b)
        self.w.comboPrioWarrantyPerformance.setVisible(b)
        self.w.comboPrioCertificates.setVisible(b)
        self.w.comboPrioIncoterm.setVisible(b)
        self.w.comboPrioMadeIn.setVisible(b)
        self.w.comboPrioOrigin.setVisible(b)
        self.w.comboPrioDestination.setVisible(b)
